# 医学术语标准化映射表
# 用于将常见的医学术语映射到标准化名称

# 心血管疾病
'心梗': '心肌梗死'
'心梦': '心肌梗死'
'冠心病': '冠状动脉粥样硬化性心脏病'
'高血压': '高血压病'
'心衰': '心力衰竭'
'房颤': '心房颤动'
'动脉硬化': '动脉粥样硬化'
'胸痛': '胸部疼痛'
'心绞痛': '冠状动脉缺血性疼痛'

# 呼吸系统疾病
'肺炎': '肺部感染'
'慢阻肺': '慢性阻塞性肺疾病'
'哮喘': '支气管哮喘'
'肺结核': '结核病肺部感染'
'呼吸衰竭': '呼吸功能不全'

# 内分泌系统疾病
'糖尿病': '糖尿病'
'甲减': '甲状腺功能减退症'
'甲亢': '甲状腺功能亢进症'
'肥胖症': '病态性肥胖'

# 消化系统疾病
'胃炎': '胃黏膜炎症'
'胃溃疡': '胃黏膜溃疡'
'胃癌': '胃恶性肿瘤'
'肝炎': '肝脏炎症'
'肝硬化': '肝纤维化晚期'
'胆结石': '胆囊结石'
'结肠炎': '结肠黏膜炎症'

# 神经系统疾病
'脑卒中': '脑血管意外'
'脑梗': '脑梗死'
'偏瘫': '一侧肢体瘫痪'
'帕金森': '帕金森病'
'阿尔兹海默': '阿尔兹海默病'
'癫痫': '癫痫发作'
'头痛': '头部疼痛'
'偏头痛': '血管性头痛'

# 泌尿系统疾病
'肾炎': '肾小球肾炎'
'肾衰': '肾功能不全'
'尿毒症': '终末期肾病'
'前列腺炎': '前列腺组织炎症'
'前列腺增生': '良性前列腺增生'

# 常见的医疗术语
'CT': '计算机断层扫描'
'核磁': '磁共振成像'
'B超': '超声波检查'
'心电图': '心电图检查'
'胸片': '胸部X线检查'

# 治疗方式
'PCI': '经皮冠状动脉介入术'
'支架': '冠状动脉支架植入术'
'搭桥': '冠状动脉旁路移植术'
'CABG': '冠状动脉旁路移植术'
'溶栓': '血栓溶解治疗'
'抗凝': '抗凝血治疗'
'抗血小板': '抗血小板聚集治疗'
'利尿': '利尿治疗'
'降压': '降血压治疗'
'降糖': '降血糖治疗'
'降脂': '降血脂治疗'
'化疗': '化学药物治疗'
'放疗': '放射线治疗'
'靶向治疗': '分子靶向治疗'
'免疫治疗': '免疫调节治疗'
'透析': '血液透析治疗'
'呼吸机': '机械通气治疗'

# 药物类别
'阿司匹林': '乙酰水杨酸'
'阿托伐他汀': 'HMG-CoA还原酶抑制剂'
'卡托普利': '血管紧张素转换酶抑制剂'
'洛沙坦': '血管紧张素II受体拮抗剂'
'二甲双胍': '双胍类降糖药'
'胰岛素': '胰岛素制剂'
